default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_DATABASE'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default

production:
  <<: *default